### ISSUE TITLE
Visual issues since last patch

### ISSUE THREAD

**Issue by DavidBabel** [Lombra/SpellBinding#1]
Hello ! 

I love this addon but it seems to have glitch issues since last patch : 
![image](https://user-images.githubusercontent.com/5599375/219680233-016305b5-e4bc-4be2-bbf6-3d9b3385e838.png)

Seems only visual because by forcing a bit, the addon itself is still usable

**Comment by Lombra** [comment]
Hello,

Thanks for your report.

Which version and client is this? The tabs don't look like retail, and the text on the "Bind interface" button has clearly been modified, so I can't really tell what I am working with here.

**Comment by Lombra** [comment]
Should be fixed in 1.0.4.
